version: "3.9"
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./python/Dockerfile
    image: "name001/pymysql"
    container_name: pymysqlclient
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      - MYSQL_DATABASE=python_sample
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker